### ISSUE TITLE
escape from single read fastqs

### ISSUE THREAD

**Issue by omarkr8** [avierstr/amplicon_sorter#10]
Hi, 

perhaps an unintentional bug, but I ran my loop on a folder of fastqs, it got stuck at a fastq containing a single read (presumably it would also get stuck if it filters down to a single read).

Of course we would normally just exclude these fastqs beforehand, but i didnt think to do so. the software was stuck at the " reading random 1 out of 1 sequences " bit for 5 hours before i terminated it. Presumably it cant go on to do comparisons if theres nothing else to compare to. 

Im solving this on my end by incorporating a ifthen continue to my loop, skipping barcodes with fewer than x reads.
but perhaps a built in escape would be good. 

im still using the current release

**Comment by avierstr** [comment]
Ok, thanks for the notice.  I'll incorporate it.

**Comment by avierstr** [comment]
fixed in version 2023-03-12
