### ISSUE TITLE
ampliconsorter frozen

### ISSUE THREAD

**Issue by capoony** [avierstr/amplicon_sorter#15]
Hi Andy, 

I am facing a rather curious problem. When starting ampliconsorter with an admittedly small dataset (no more reads available), ampliconsorter freezes and never stops running. I have used the following settings:

```bash 
./ampliconsorter.py  \
   -i AATS.fastq  \
   -np 1 \
   -maxr 500 \
   -o output/
```
I have attached the `AATS.fastq` (gzipped) for reproduciblity.

Thanks, Martin
[AATS.fastq.gz](https://github.com/avierstr/amplicon_sorter/files/14221694/AATS.fastq.gz)

**Comment by avierstr** [comment]
Hi Martin,

I'm having the same result with your file.  When printing the readlengths, it seems that they are to different in length (max 1.05 difference allowed to compare them with each other).  So nothing has to be done according to the script but that exceptional occurrence  is not catched in an exit of the program.  I will update it so it exits when this happens.

Best regards,
Andy

```
python3 amplicon_sorter.py -i AATS.fastq -np 1 -maxr 500 -o output
Reading AATS.fastq
1261
427
333
303
877
700
753
AATS.fastq contains 7 reads.
--> Low number of reads, reading all 7 out of 7 sequences longer than 300bp
```

**Comment by capoony** [comment]
Hi Andy, wow!! Thanks for your light-speed response and for looking into this! I was suspecting something like this.

best regards, 

Martin

**Comment by capoony** [comment]
Hi Andy, sorry for being a pain, but when do you expect a fix? Alternatively, we could also have a try and commit on a different branch. many thanks! :-)

Best, Martin

**Comment by avierstr** [comment]
Hi Martin,
I did not look into that because I did not know it was urgent.  It was only a small fix.  Here is the updated file.  I will upload it to the main branch one of the next days.
Best regards,
Andy
[amplicon_sorter_2024_02_20.py.zip](https://github.com/avierstr/amplicon_sorter/files/14349891/amplicon_sorter_2024_02_20.py.zip)

**Comment by capoony** [comment]
Dear Andy,

oh my, sorry! Hope I did not stress you! Thanks a lot, I'll test the new versions asap.

Many greetings, 

Martin

**Comment by capoony** [comment]
Thanks Andy, works like a charm! 

Many greetings, 

Martin
