### ISSUE TITLE
Problem in tmp file not found

### ISSUE THREAD

**Issue by cocoaawil** [avierstr/amplicon_sorter#20]
Dear Sirs, I have some problem about tmp file which was not created. I ran the job in linux server. There is some error in below:

passedQC_iF02_iR09.fasta contains 17 reads.
--> Low number of reads, reading all 17 out of 17 sequences between 1350 and 1650bp
processing: file_0.todo
Estimating the ssg value for this dataset
Traceback (most recent call last):
  File "amplicon_sorter.py", line 2081, in <module>
    sort_groups()
  File "amplicon_sorter.py", line 2000, in sort_groups
    grouplist = update_list(tempfile)
  File "amplicon_sorter.py", line 944, in update_list
    estimated_ssg = SSG(tempfile) # estimate ssg value
  File "amplicon_sorter.py", line 795, in SSG
    with open(tempfile, 'r') as tf:
FileNotFoundError: [Errno 2] No such file or directory: 'passedQC_iF02_iR09_compare.tmp'

I'm not sure that how should I solve this problem. Could you please suggest me?

**Comment by avierstr** [comment]
I think the problem is the low number of reads.  These are probably to different from each other for the program to find 2 or more sequences to create consensus.  If you blast those reads, are they the same species ?

**Comment by cocoaawil** [comment]
Thank you very much for your response. I tried to run one job in the same sample between two servers based on linux system. One server based on python3.6, job was completed but other server based on python3, job did not complete because of tmp not found like that. I'm not sure that It maybe python version or not.

**Comment by tylerch9999** [comment]
I am having a similar issue. Macbook, using python3.12.7, and using ~1,000 reads (100bp each) from short amplicon sequencing.

**Comment by avierstr** [comment]
Hi Tylerch9999,
Does your macbook has a M1 processor ?  That can cause that error.
see:
https://github.com/avierstr/amplicon_sorter/issues/14
In the last comment there, I have put a extra version you can donwload with an extra command option (-mac).  Can you try if that solves the problem ?
Best regards,
Andy

**Comment by avierstr** [comment]
I have now added an single core version that should work:
[amplicon_sorter_single.py](https://github.com/avierstr/amplicon_sorter/blob/master/amplicon_sorter_single.py)
