### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Hanjiewu** [avierstr/amplicon_sorter#4]
Hi, I git clone the amplicon_sorter and installed dependencies as specified in the manual.
but when I ran the amplicon_sorter.py I got the following message:
/usr/bin/env: 'python3\r': No such file or directory

Can you help to id the problem?

Thanks

**Comment by avierstr** [comment]
what do you get when you type:
python
or when you type:
python3

On 31/08/2022 8:46, Hanjiewu wrote:
>
> Hi, I git clone the amplicon_sorter and installed dependencies as 
> specified in the manual.
> but when I ran the amplicon_sorter.py I got the following message:
> /usr/bin/env: 'python3\r': No such file or directory
>
> Can you help to id the problem?
>
> Thanks
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F4&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C834f9e3df69f4530f0de08da8b1c9ada%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975252212397741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xZzVynT6Tv9%2BSdVYrgdur3K5pmDOT5uFaHlfvWQqIdg%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYSMXOTFNNO6Q2NOZTLV335WFANCNFSM6AAAAAAQBCGE3U&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C834f9e3df69f4530f0de08da8b1c9ada%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975252212397741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Jbzys7PTJcmf9y7VABvUPPJJp1sgWJgYvmgMQADdufo%3D&reserved=0>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by Hanjiewu** [comment]
type: python or python3
message:
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by avierstr** [comment]
So python is installed.

if you type:
python amplicon_sorter.py

that should work then ?

On 31/08/2022 12:57, Hanjiewu wrote:
>
> type: python or python3
> message:
> Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F4%23issuecomment-1232784796&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C11a1a0854ded477ef0d908da8b3f9b91%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975402557246055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6VE%2BFFqXZLve%2Fq0RDgAf81TTQmjNBKh1srPBXBjaGTw%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYX3MKTXWCS3NDCI223V343BZANCNFSM6AAAAAAQBCGE3U&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C11a1a0854ded477ef0d908da8b3f9b91%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975402557402298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y3FKtOLf%2FLddt0HbhREBMz5wu5q1NcJOQIir0BYZRFw%3D&reserved=0>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by Hanjiewu** [comment]
It works, thank you so much, I am newbie in this.

One thing though,  I ran the script and it showed:
```
Reading BC01.fastq
BC01.fastq contains 11924 reads.
--> Reading random 1000 out of 10420 sequences between 100 and 700bp
processing: file_0.todo
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/amplicon_sorter/amplicon_sorter.py", line 554, in feeder
    os.remove(os.path.join(outputfolder, name))
OSError: [Errno 16] Device or resource busy: '/mnt/nas40T/frchen/temp/EXPT2/basecalling-SuperHighACU/pass/Run1/Output/file_0.todo'

```
It seems the system freezes up and hasn't changed for more than 1 hour, should I wait or it is not working as expected?

**Comment by avierstr** [comment]
No, you don't have to wait, it crashed.

The error message is that it can not remove the file because it is still 
busy.  Are you working on an external harddisk ?  Maybe the time to read 
and write to that disk is too long.

Can you copy the file to the internal harddisk and try again ?

Best regards,
Andy

On 31/08/2022 15:55, Hanjiewu wrote:
>
> It works, thank you so much, I am newbie in this.
>
> One thing though, I ran the script and it showed:
>
> |Reading BC01.fastq BC01.fastq contains 11924 reads. --> Reading 
> random 1000 out of 10420 sequences between 100 and 700bp processing: 
> file_0.todo Exception in thread Thread-2: Traceback (most recent call 
> last): File "/root/miniconda3/lib/python3.7/threading.py", line 926, 
> in _bootstrap_inner self.run() File 
> "/root/miniconda3/lib/python3.7/threading.py", line 870, in run 
> self._target(*self._args, **self._kwargs) File 
> "/opt/amplicon_sorter/amplicon_sorter.py", line 554, in feeder 
> os.remove(os.path.join(outputfolder, name)) OSError: [Errno 16] Device 
> or resource busy: 
> '/mnt/nas40T/frchen/temp/EXPT2/basecalling-SuperHighACU/pass/Run1/Output/file_0.todo' 
> |
>
> It seems the system freezes up and hasn't changed for more than 1 
> hour, should I wait or it is not working as expected?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F4%23issuecomment-1232972269&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Ca599c37560fe4d0f8c8c08da8b586bfa%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975509155078058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gtDZHM6PH9igMMJTEDnKkqUVghNdCyVLIA9jR%2BS6qWY%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYXNTRM7AI7WYLZFPJ3V35P33ANCNFSM6AAAAAAQBCGE3U&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Ca599c37560fe4d0f8c8c08da8b586bfa%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637975509155078058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UvECK5coXk0vp7M%2BxNd5aKcARMHdKS43vvHDaKltmxc%3D&reserved=0>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by Hanjiewu** [comment]
It worked after copying the file to the internal hard disk.
Thank you for the walk-through, much appreciated !

One more thing, I noticed the headers of the grouped reads were replaced with a number. Is there a way to trace back to its original read ID?

Thank you

**Comment by avierstr** [comment]
Yes, you can use the option "-sfq" (also save the files as fastq and not 
only as fasta).  In the fastq files the original ID's are saved (but not 
the consensus read at the end of the file).

Happy it works,
Andy

On 1/09/2022 8:33, Hanjiewu wrote:
>
> It worked after copying the file to the internal hard disk.
> Thank you for the walk-through, much appreciated !
>
> One more thing, I noticed the headers of the grouped reads were 
> replaced with a number. Is there a way to trace back to its original 
> read ID?
>
> Thank you
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F4%23issuecomment-1233807772&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Cdaa43e095a0f4ae418d908da8be3e870%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637976108218891139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AwBx9gz3fRFcxxBEwNP9KyA4tDOmrxZYpZoinkhhAz8%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYW2VM45IAO22NMONBTV4BE4FANCNFSM6AAAAAAQBCGE3U&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Cdaa43e095a0f4ae418d908da8be3e870%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637976108218891139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tFqvH4%2Fglf6WrZ0enTDi4HVmmw5BQ4BYY9kQ%2FTar6lQ%3D&reserved=0>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by avierstr** [comment]
I have noticed when amplicon_sorter is used on cloud drives like Onedrive, Pcloud, Google drive, Dropbox, ... that is crashes at some time.  That is because it is writing and reading temp files to and from the drive.  There is a delay in those cloud drives that gives problems.  Copy your data to a local harddisk and process it.
