### ISSUE TITLE
.tmp file not found

### ISSUE THREAD

**Issue by bugsoundsjc** [avierstr/amplicon_sorter#5]
Hello, when running amplicon sorter a FileNotFound error for the .tmp file hangs up the run. The .pickle file shows up in the output but no .tmp. I am running amplicon_sorter in Miniconda Python 3.9. Thanks for any ideas about how to proceed!

```Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 586, in similarity
    similarg = args.similar_genes/100
NameError: name 'args' is not defined
Estimating the ssg value for this dataset
Traceback (most recent call last):
  File "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 1823, in <module>
    sort_groups()
  File "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 1770, in sort_groups
    update_list(tempfile)
  File "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 767, in update_list
    estimated_ssg = SSG(tempfile) # estimate ssg value
  File "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 618, in SSG
    with open(tempfile, 'r') as tf:
FileNotFoundError: [Errno 2] No such file or directory: 'barcode01_qc12_compare.tmp'
^[[A^[[B^CException ignored in: <module 'threading' from '/opt/miniconda3/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/threading.py", line 1477, in _shutdown
    lock.acquire()
```

**Comment by avierstr** [comment]
my suspicion is that there were not enough similar reads in the 
inputfile.  What command did you use to run amplicon_sorter ?

On 6/09/2022 23:04, bugsoundsjc wrote:
>
> Hello, when running amplicon sorter a FileNotFound error for the .tmp 
> file hangs up the run. The .pickle file shows up in the output but no 
> .tmp. I am running amplicon_sorter in Miniconda Python 3.9. Thanks for 
> any ideas about how to proceed!
>
> |File "/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 
> 315, in _bootstrap self.run() File 
> "/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, 
> in run self._target(*self._args, **self._kwargs) File 
> "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 586, in 
> similarity similarg = args.similar_genes/100 NameError: name 'args' is 
> not defined Estimating the ssg value for this dataset Traceback (most 
> recent call last): File 
> "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 1823, in 
> <module> sort_groups() File 
> "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 1770, in 
> sort_groups update_list(tempfile) File 
> "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 767, in 
> update_list estimated_ssg = SSG(tempfile) # estimate ssg value File 
> "/Users/jac/amplicon_sorter-master/amplicon_sorter.py", line 618, in 
> SSG with open(tempfile, 'r') as tf: FileNotFoundError: [Errno 2] No 
> such file or directory: 'barcode01_qc12_compare.tmp' 
> ^[[A^[[B^CException ignored in: <module 'threading' from 
> '/opt/miniconda3/lib/python3.9/threading.py'> Traceback (most recent 
> call last): File "/opt/miniconda3/lib/python3.9/threading.py", line 
> 1477, in _shutdown lock.acquire() |
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F5&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C95911695c3da4b32792108da904b712c%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637980950937908100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JltnAlGaPcGbE1z59bO%2BmX9WjG%2FyjyAA9FdF0mr%2F99I%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYWUGAD5DXDLL756PZDV46WXFANCNFSM6AAAAAAQGF6PHU&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C95911695c3da4b32792108da904b712c%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637980950937908100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Saucv1B%2BQRk%2Fa2JaqzbayDMA4YgROaQwwZwf6FM7glM%3D&reserved=0>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by bugsoundsjc** [comment]
Thanks, that could be the case after checking the read qualities of the ONT data. Tried one amplicon of interest out of a multiplexed dataset to test out the procedure. This was the command:
`(base) jac@Jeffreys-MBP ~ % python3 /Users/jac/amplicon_sorter-master/amplicon_sorter.py -i /Users/jac/amplicon_sorter-master/barcode01_qc12.fastq -o /Users/jac/amplicon_sorter-master/HUbc01sorted -np 4 -min 750 -max 850 -ra -maxr 1000
`

**Comment by avierstr** [comment]
So is it working now with reads of better quality or more reads ?

On 8/09/2022 1:55, bugsoundsjc wrote:
>
> Thanks, that could be the case after checking the read qualities of 
> the ONT data. Tried one amplicon of interest out of a multiplexed 
> dataset to test out the procedure. This was the command:
> |(base) ***@***.*** ~ % python3 
> /Users/jac/amplicon_sorter-master/amplicon_sorter.py -i 
> /Users/jac/amplicon_sorter-master/barcode01_qc12.fastq -o 
> /Users/jac/amplicon_sorter-master/HUbc01sorted -np 4 -min 750 -max 850 
> -ra -maxr 1000 |
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F5%23issuecomment-1240031323&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C93be4ffc977f43f5d72708da912c7a59%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637981917469578081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ckK9rUj0Tlz3sN6ysWhXf%2B81dTTSJhVfZe3q0EICBh8%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYQZ2LMJAXYAJUI3V4LV5ETP5ANCNFSM6AAAAAAQGF6PHU&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7C93be4ffc977f43f5d72708da912c7a59%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637981917469578081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sQTS%2BtRKDRPyrUk%2B6e0NXf%2FhIUAwQr5hd8g87%2F27NK0%3D&reserved=0>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by bugsoundsjc** [comment]
Haven't had a chance to work with it more, I will let you know!

**Comment by bugsoundsjc** [comment]
Finally tried amplicon sorter again, this time with the sample dataset on Dryad. The same errors above come up, 'args' not defined and a compare.tmp file not found. The .pickle file and outputfolder with a results.txt appear. I'm running amplicon_sorter from a miniconda environment with python 3 that has the dependencies. The read length histogram works fine.

**Comment by avierstr** [comment]
Did you try again with -maxr 1000 or did you try more reads ?

**Comment by bugsoundsjc** [comment]
This time I tried -maxr 2000 and 10000 e.g.
python3 amplicon_sorter.py -i HAC.fastq -o outputfolder -np 8 -min 650 -max 2850 -maxr 10000

**Comment by avierstr** [comment]
I still have the suspicion that there are not enough reads sampled that are similar.  Do you have a peak in the read length histogram from an abundant amplicon ?  If so can you try with a limited range in read length ?  Suppose you have a peak at 700 bp: 
python3 amplicon_sorter.py -i HAC.fastq -o outputfolder -np 8 -min 650 -max 750 -maxr 10000

**Comment by bugsoundsjc** [comment]
Same result. Might this have to do with my version of Python and dependencies?

**Comment by bugsoundsjc** [comment]
With a Homebrew install of Python3 and packages on another computer, it now moves past that error and is apparently processing HAC.fastq.

**Comment by avierstr** [comment]
ok, it means there was something wrong with the python installation on 
the other computer.
Problem solved :-)
